/*
 * MedPharm ERP - macOS Application
 * Copyright (C) 2026 Enlightec Ltd. (www.enlightec.com)
 * Author: Robert Andrew Stillwell
 * Email: Andrew.Stillwell@enlightec.com
 * License: GNU General Public License v3.0
 *
 * QRConfigParser — Normalises a pasted/scanned string to an API base URL.
 * Mirrors the iOS implementation so a QR generated by the server-side
 * `start_ngrok.sh` helper feeds either client identically.
 */

import Foundation

enum QRConfigParser {
    static func normalize(_ raw: String) -> String {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return "" }

        if trimmed.hasPrefix("{"), let data = trimmed.data(using: .utf8) {
            if let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
                if let v = obj["api_base_url"] as? String, !v.isEmpty { return v }
                if let v = obj["public_url"] as? String, !v.isEmpty {
                    return appendingApiSuffixIfMissing(v)
                }
            }
        }

        if trimmed.lowercased().hasPrefix("http://") || trimmed.lowercased().hasPrefix("https://") {
            return appendingApiSuffixIfMissing(trimmed)
        }

        return trimmed
    }

    private static func appendingApiSuffixIfMissing(_ url: String) -> String {
        let stripped = url.hasSuffix("/") ? String(url.dropLast()) : url
        if stripped.contains("/api/") {
            return stripped
        }
        return stripped + "/api/v1"
    }
}
