<!--
  MedPharm ERP - Windows Desktop Application
  Copyright (C) 2026 Enlightec Ltd. (www.enlightec.com)
  Author: Robert Andrew Stillwell
  License: GNU General Public License v3.0
-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>MedPharm</RootNamespace>
    <AssemblyName>MedPharm</AssemblyName>
    <Version>1.1.0</Version>
    <Company>Enlightec Ltd.</Company>
    <Product>MedPharm ERP</Product>
    <Copyright>Copyright (C) 2026 Enlightec Ltd.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
  </ItemGroup>

</Project>
