# MedPharm ERP - Medical & Pharmaceutical Management System
# Copyright (C) 2026 Enlightec Ltd. (www.enlightec.com)
# Author: Robert Andrew Stillwell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
MedPharm ERP - Expanded Seed Data
Comprehensive symptoms, conditions, and additional medications database.
Called after the base seed_database() to enrich the reference data.
"""

from medical_erp.database.db_manager import DatabaseManager
from medical_erp.database.models import (
    Symptom, Condition, Medication, InsuranceClaim, InsuranceClaimStatus,
    DrugSchedule, DrugRoute, DrugForm
)


def seed_expanded_data(db_manager: DatabaseManager):
    """Seed expanded reference data if not already present."""
    with db_manager.get_session() as session:
        if session.query(Symptom).count() > 0:
            return

        # ── Symptoms Database (80+) ───────────────────────────────────
        symptoms = [
            # Cardiovascular
            Symptom(name="Chest Pain", body_system="Cardiovascular",
                    description="Pain or discomfort in the chest area, may radiate to arms, jaw, or back",
                    icd10_codes="R07.9", common_conditions="Angina, MI, GERD, Costochondritis", is_emergency=True),
            Symptom(name="Palpitations", body_system="Cardiovascular",
                    description="Awareness of heartbeat; may feel rapid, fluttering, or pounding",
                    icd10_codes="R00.2", common_conditions="Arrhythmia, Anxiety, Hyperthyroidism"),
            Symptom(name="Shortness of Breath", body_system="Cardiovascular",
                    description="Difficulty breathing or feeling of not getting enough air",
                    icd10_codes="R06.0", common_conditions="Heart failure, Asthma, COPD, Anxiety", is_emergency=True),
            Symptom(name="Edema (Swelling)", body_system="Cardiovascular",
                    description="Swelling in legs, ankles, or feet due to fluid retention",
                    icd10_codes="R60.0", common_conditions="Heart failure, Venous insufficiency, Kidney disease"),
            Symptom(name="Dizziness/Lightheadedness", body_system="Cardiovascular",
                    description="Feeling faint, unsteady, or sensation of spinning",
                    icd10_codes="R42", common_conditions="Orthostatic hypotension, Arrhythmia, Anemia"),
            Symptom(name="Syncope (Fainting)", body_system="Cardiovascular",
                    description="Temporary loss of consciousness due to reduced blood flow to brain",
                    icd10_codes="R55", common_conditions="Vasovagal, Cardiac arrhythmia, Orthostatic", is_emergency=True),

            # Respiratory
            Symptom(name="Cough (Acute)", body_system="Respiratory",
                    description="Sudden onset cough lasting less than 3 weeks",
                    icd10_codes="R05.9", common_conditions="URI, Bronchitis, Pneumonia, COVID-19"),
            Symptom(name="Cough (Chronic)", body_system="Respiratory",
                    description="Persistent cough lasting more than 8 weeks",
                    icd10_codes="R05.9", common_conditions="Asthma, GERD, Post-nasal drip, ACE inhibitor"),
            Symptom(name="Wheezing", body_system="Respiratory",
                    description="High-pitched whistling sound during breathing",
                    icd10_codes="R06.2", common_conditions="Asthma, COPD, Bronchitis, Allergic reaction"),
            Symptom(name="Hemoptysis", body_system="Respiratory",
                    description="Coughing up blood or blood-tinged sputum",
                    icd10_codes="R04.2", common_conditions="Bronchitis, Pneumonia, TB, Lung cancer", is_emergency=True),
            Symptom(name="Sore Throat", body_system="Respiratory",
                    description="Pain, scratchiness, or irritation of the throat",
                    icd10_codes="R07.0", common_conditions="Pharyngitis, Strep throat, Tonsillitis, GERD"),
            Symptom(name="Nasal Congestion", body_system="Respiratory",
                    description="Stuffy nose due to swollen nasal tissues and blood vessels",
                    icd10_codes="R09.81", common_conditions="Common cold, Allergies, Sinusitis"),

            # Gastrointestinal
            Symptom(name="Abdominal Pain", body_system="Gastrointestinal",
                    description="Pain in the area between chest and groin",
                    icd10_codes="R10.9", common_conditions="Gastritis, IBS, Appendicitis, Gallstones"),
            Symptom(name="Nausea", body_system="Gastrointestinal",
                    description="Sensation of unease and discomfort in stomach with urge to vomit",
                    icd10_codes="R11.0", common_conditions="Gastroenteritis, Pregnancy, Medication side effect"),
            Symptom(name="Vomiting", body_system="Gastrointestinal",
                    description="Forceful expulsion of stomach contents through the mouth",
                    icd10_codes="R11.1", common_conditions="Gastroenteritis, Food poisoning, Migraine"),
            Symptom(name="Diarrhea", body_system="Gastrointestinal",
                    description="Loose, watery stools occurring more frequently than usual",
                    icd10_codes="R19.7", common_conditions="Gastroenteritis, IBS, C. diff, Food intolerance"),
            Symptom(name="Constipation", body_system="Gastrointestinal",
                    description="Infrequent bowel movements or difficulty passing stools",
                    icd10_codes="K59.0", common_conditions="IBS, Medication side effect, Hypothyroidism"),
            Symptom(name="Heartburn/GERD", body_system="Gastrointestinal",
                    description="Burning sensation in chest/throat from acid reflux",
                    icd10_codes="K21.0", common_conditions="GERD, Hiatal hernia, Peptic ulcer"),
            Symptom(name="Bloating", body_system="Gastrointestinal",
                    description="Feeling of fullness or swelling in the abdomen",
                    icd10_codes="R14.0", common_conditions="IBS, Lactose intolerance, Celiac disease"),
            Symptom(name="Rectal Bleeding", body_system="Gastrointestinal",
                    description="Blood in stool or on toilet paper after bowel movement",
                    icd10_codes="K62.5", common_conditions="Hemorrhoids, Fissure, Diverticulosis, Colorectal cancer", is_emergency=True),

            # Neurological
            Symptom(name="Headache", body_system="Neurological",
                    description="Pain in any region of the head",
                    icd10_codes="R51.9", common_conditions="Tension headache, Migraine, Cluster headache"),
            Symptom(name="Migraine", body_system="Neurological",
                    description="Severe throbbing headache often with nausea and light sensitivity",
                    icd10_codes="G43.9", common_conditions="Migraine with/without aura"),
            Symptom(name="Numbness/Tingling", body_system="Neurological",
                    description="Loss of sensation or pins-and-needles feeling in extremities",
                    icd10_codes="R20.0", common_conditions="Peripheral neuropathy, Carpal tunnel, MS, Diabetes"),
            Symptom(name="Tremor", body_system="Neurological",
                    description="Involuntary rhythmic shaking movement",
                    icd10_codes="R25.1", common_conditions="Essential tremor, Parkinson's, Medication side effect"),
            Symptom(name="Seizure", body_system="Neurological",
                    description="Sudden uncontrolled electrical disturbance in the brain",
                    icd10_codes="R56.9", common_conditions="Epilepsy, Febrile seizure, Brain injury", is_emergency=True),
            Symptom(name="Memory Loss", body_system="Neurological",
                    description="Unusual forgetfulness; difficulty recalling events or information",
                    icd10_codes="R41.3", common_conditions="Alzheimer's, Dementia, Depression, B12 deficiency"),
            Symptom(name="Confusion", body_system="Neurological",
                    description="Inability to think clearly; disorientation",
                    icd10_codes="R41.0", common_conditions="Delirium, Infection, Metabolic disorder, Stroke", is_emergency=True),

            # Musculoskeletal
            Symptom(name="Back Pain", body_system="Musculoskeletal",
                    description="Pain in the upper, middle, or lower back",
                    icd10_codes="M54.9", common_conditions="Muscle strain, Herniated disc, Arthritis, Sciatica"),
            Symptom(name="Joint Pain", body_system="Musculoskeletal",
                    description="Discomfort, ache, or soreness in any joint",
                    icd10_codes="M25.5", common_conditions="Osteoarthritis, Rheumatoid arthritis, Gout"),
            Symptom(name="Muscle Pain", body_system="Musculoskeletal",
                    description="Aching or soreness in muscles",
                    icd10_codes="M79.1", common_conditions="Fibromyalgia, Overuse, Viral infection, Statin use"),
            Symptom(name="Joint Swelling", body_system="Musculoskeletal",
                    description="Enlargement or puffiness around a joint",
                    icd10_codes="M25.4", common_conditions="Arthritis, Gout, Injury, Infection"),
            Symptom(name="Neck Pain", body_system="Musculoskeletal",
                    description="Pain in the cervical spine area",
                    icd10_codes="M54.2", common_conditions="Cervical strain, Herniated disc, Whiplash"),
            Symptom(name="Stiffness", body_system="Musculoskeletal",
                    description="Difficulty moving a joint or muscle through full range of motion",
                    icd10_codes="M25.6", common_conditions="Osteoarthritis, RA, Ankylosing spondylitis"),

            # Dermatological
            Symptom(name="Rash", body_system="Dermatological",
                    description="Change in skin color, texture, or appearance",
                    icd10_codes="R21", common_conditions="Allergic reaction, Eczema, Psoriasis, Drug reaction"),
            Symptom(name="Itching (Pruritus)", body_system="Dermatological",
                    description="Uncomfortable sensation causing desire to scratch",
                    icd10_codes="L29.9", common_conditions="Eczema, Allergies, Liver disease, Dry skin"),
            Symptom(name="Hives (Urticaria)", body_system="Dermatological",
                    description="Raised, itchy welts on the skin",
                    icd10_codes="L50.9", common_conditions="Allergic reaction, Medication reaction, Stress"),
            Symptom(name="Skin Lesion", body_system="Dermatological",
                    description="Abnormal area of skin (mole, growth, or sore)",
                    icd10_codes="L98.9", common_conditions="Basal cell carcinoma, Melanoma, Benign nevus"),
            Symptom(name="Hair Loss", body_system="Dermatological",
                    description="Thinning or loss of hair from scalp or body",
                    icd10_codes="L65.9", common_conditions="Alopecia, Thyroid disease, Iron deficiency, Stress"),

            # Endocrine/Metabolic
            Symptom(name="Fatigue", body_system="Endocrine",
                    description="Persistent tiredness not relieved by rest",
                    icd10_codes="R53.83", common_conditions="Hypothyroidism, Anemia, Depression, Diabetes"),
            Symptom(name="Weight Gain (Unintentional)", body_system="Endocrine",
                    description="Increase in body weight without trying",
                    icd10_codes="R63.5", common_conditions="Hypothyroidism, Cushing's, PCOS, Medication"),
            Symptom(name="Weight Loss (Unintentional)", body_system="Endocrine",
                    description="Decrease in body weight without trying",
                    icd10_codes="R63.4", common_conditions="Hyperthyroidism, Cancer, Diabetes, Depression"),
            Symptom(name="Excessive Thirst", body_system="Endocrine",
                    description="Abnormally increased thirst (polydipsia)",
                    icd10_codes="R63.1", common_conditions="Diabetes mellitus, Diabetes insipidus, Dehydration"),
            Symptom(name="Frequent Urination", body_system="Endocrine",
                    description="Need to urinate more often than usual (polyuria)",
                    icd10_codes="R35.0", common_conditions="Diabetes, UTI, BPH, Diuretic use"),
            Symptom(name="Heat/Cold Intolerance", body_system="Endocrine",
                    description="Abnormal sensitivity to heat or cold",
                    icd10_codes="R68.89", common_conditions="Hyperthyroidism, Hypothyroidism, Menopause"),

            # Psychiatric
            Symptom(name="Depressed Mood", body_system="Psychiatric",
                    description="Persistent feeling of sadness or hopelessness",
                    icd10_codes="R45.2", common_conditions="Major depression, Bipolar disorder, Adjustment disorder"),
            Symptom(name="Anxiety", body_system="Psychiatric",
                    description="Excessive worry, nervousness, or unease",
                    icd10_codes="R45.1", common_conditions="GAD, Panic disorder, Social anxiety, PTSD"),
            Symptom(name="Insomnia", body_system="Psychiatric",
                    description="Difficulty falling or staying asleep",
                    icd10_codes="G47.0", common_conditions="Anxiety, Depression, Sleep apnea, Medication"),
            Symptom(name="Panic Attacks", body_system="Psychiatric",
                    description="Sudden episodes of intense fear with physical symptoms",
                    icd10_codes="F41.0", common_conditions="Panic disorder, GAD, PTSD, Phobia"),
            Symptom(name="Mood Swings", body_system="Psychiatric",
                    description="Rapid, unexplained changes in emotional state",
                    icd10_codes="R45.89", common_conditions="Bipolar disorder, PMS/PMDD, Borderline PD"),
            Symptom(name="Difficulty Concentrating", body_system="Psychiatric",
                    description="Trouble focusing or maintaining attention",
                    icd10_codes="R41.840", common_conditions="ADHD, Depression, Anxiety, Sleep deprivation"),
            Symptom(name="Hallucinations", body_system="Psychiatric",
                    description="Perceiving things not present (visual, auditory)",
                    icd10_codes="R44.3", common_conditions="Schizophrenia, Delirium, Substance use", is_emergency=True),

            # Urological
            Symptom(name="Painful Urination", body_system="Urological",
                    description="Burning or pain during urination (dysuria)",
                    icd10_codes="R30.0", common_conditions="UTI, STI, Prostatitis, Interstitial cystitis"),
            Symptom(name="Blood in Urine", body_system="Urological",
                    description="Presence of blood in urine (hematuria)",
                    icd10_codes="R31.9", common_conditions="UTI, Kidney stones, Bladder cancer, Prostate"),
            Symptom(name="Urinary Incontinence", body_system="Urological",
                    description="Involuntary loss of urine",
                    icd10_codes="R32", common_conditions="Stress incontinence, Overactive bladder, BPH"),
            Symptom(name="Flank Pain", body_system="Urological",
                    description="Pain in the side between upper abdomen and back",
                    icd10_codes="R10.9", common_conditions="Kidney stones, Pyelonephritis, Renal colic"),

            # Eyes/ENT
            Symptom(name="Blurred Vision", body_system="Ophthalmological",
                    description="Loss of sharpness of vision",
                    icd10_codes="H53.8", common_conditions="Refractive error, Cataracts, Diabetes, Glaucoma"),
            Symptom(name="Eye Pain", body_system="Ophthalmological",
                    description="Pain in or around the eye",
                    icd10_codes="H57.1", common_conditions="Glaucoma, Uveitis, Corneal abrasion, Migraine"),
            Symptom(name="Ear Pain", body_system="ENT",
                    description="Pain inside or around the ear (otalgia)",
                    icd10_codes="H92.0", common_conditions="Otitis media, Otitis externa, TMJ, Referred pain"),
            Symptom(name="Hearing Loss", body_system="ENT",
                    description="Partial or complete inability to hear",
                    icd10_codes="H91.9", common_conditions="Presbycusis, Noise exposure, Otosclerosis, Meniere's"),
            Symptom(name="Tinnitus", body_system="ENT",
                    description="Ringing, buzzing, or other sounds in the ears",
                    icd10_codes="H93.1", common_conditions="Noise exposure, Meniere's, Medication, Aging"),

            # General/Constitutional
            Symptom(name="Fever", body_system="General",
                    description="Elevated body temperature above 100.4F (38C)",
                    icd10_codes="R50.9", common_conditions="Infection, Inflammation, Malignancy"),
            Symptom(name="Chills", body_system="General",
                    description="Feeling of coldness with shivering",
                    icd10_codes="R68.83", common_conditions="Infection, Fever, Hypothermia"),
            Symptom(name="Night Sweats", body_system="General",
                    description="Excessive sweating during sleep",
                    icd10_codes="R61", common_conditions="Infection, Lymphoma, Menopause, TB"),
            Symptom(name="Swollen Lymph Nodes", body_system="General",
                    description="Enlarged lymph nodes in neck, armpits, or groin",
                    icd10_codes="R59.9", common_conditions="Infection, Lymphoma, Autoimmune disease"),
            Symptom(name="Loss of Appetite", body_system="General",
                    description="Decreased desire to eat",
                    icd10_codes="R63.0", common_conditions="Depression, Cancer, Infection, Medication"),
        ]
        session.add_all(symptoms)
        session.flush()

        # ── Conditions Database (60+) ─────────────────────────────────
        conditions = [
            # Cardiovascular
            Condition(name="Essential Hypertension", icd10_code="I10", category="Cardiovascular",
                      description="Persistently elevated blood pressure (>130/80 mmHg)",
                      common_symptoms="Headache, Dizziness, Blurred vision, Chest pain",
                      typical_medications="Lisinopril, Amlodipine, Losartan, Metoprolol, HCTZ",
                      prevalence="~47% of US adults", is_chronic=True),
            Condition(name="Coronary Artery Disease", icd10_code="I25.10", category="Cardiovascular",
                      description="Narrowing of coronary arteries reducing blood flow to heart",
                      common_symptoms="Chest pain, Shortness of breath, Fatigue",
                      typical_medications="Aspirin, Atorvastatin, Metoprolol, Nitroglycerin",
                      prevalence="~7% of US adults", is_chronic=True),
            Condition(name="Atrial Fibrillation", icd10_code="I48.91", category="Cardiovascular",
                      description="Irregular rapid heart rate increasing stroke risk",
                      common_symptoms="Palpitations, Fatigue, Shortness of breath, Dizziness",
                      typical_medications="Apixaban, Warfarin, Metoprolol, Diltiazem, Amiodarone",
                      prevalence="~2% of population", is_chronic=True),
            Condition(name="Heart Failure", icd10_code="I50.9", category="Cardiovascular",
                      description="Heart cannot pump blood efficiently to meet body needs",
                      common_symptoms="Shortness of breath, Edema, Fatigue, Cough",
                      typical_medications="Lisinopril, Carvedilol, Furosemide, Spironolactone",
                      prevalence="~2% of US adults", is_chronic=True),
            Condition(name="Deep Vein Thrombosis", icd10_code="I82.40", category="Cardiovascular",
                      description="Blood clot in a deep vein, usually in the leg",
                      common_symptoms="Leg swelling, Pain, Warmth, Redness",
                      typical_medications="Apixaban, Rivaroxaban, Warfarin, Heparin",
                      prevalence="~1-2 per 1000/year"),

            # Respiratory
            Condition(name="Asthma", icd10_code="J45.909", category="Respiratory",
                      description="Chronic airway inflammation causing reversible bronchoconstriction",
                      common_symptoms="Wheezing, Shortness of breath, Cough, Chest tightness",
                      typical_medications="Albuterol, Fluticasone, Montelukast, Budesonide",
                      prevalence="~8% of US population", is_chronic=True),
            Condition(name="COPD", icd10_code="J44.1", category="Respiratory",
                      description="Progressive lung disease with airflow limitation",
                      common_symptoms="Chronic cough, Shortness of breath, Wheezing, Sputum",
                      typical_medications="Tiotropium, Albuterol, Fluticasone, Prednisone",
                      prevalence="~6% of US adults", is_chronic=True),
            Condition(name="Pneumonia", icd10_code="J18.9", category="Respiratory",
                      description="Infection that inflames air sacs in one or both lungs",
                      common_symptoms="Cough, Fever, Chills, Shortness of breath, Chest pain",
                      typical_medications="Amoxicillin, Azithromycin, Levofloxacin, Doxycycline"),
            Condition(name="Allergic Rhinitis", icd10_code="J30.9", category="Respiratory",
                      description="Nasal inflammation due to allergen exposure",
                      common_symptoms="Sneezing, Nasal congestion, Runny nose, Itchy eyes",
                      typical_medications="Cetirizine, Fluticasone nasal, Loratadine, Montelukast",
                      prevalence="~20% of population", is_chronic=True),

            # Endocrine
            Condition(name="Type 2 Diabetes Mellitus", icd10_code="E11.9", category="Endocrine",
                      description="Chronic condition affecting insulin processing and blood sugar regulation",
                      common_symptoms="Excessive thirst, Frequent urination, Fatigue, Blurred vision, Weight loss",
                      typical_medications="Metformin, Glipizide, Insulin, Empagliflozin, Semaglutide",
                      prevalence="~11% of US adults", is_chronic=True),
            Condition(name="Type 1 Diabetes Mellitus", icd10_code="E10.9", category="Endocrine",
                      description="Autoimmune condition where pancreas produces little or no insulin",
                      common_symptoms="Excessive thirst, Frequent urination, Weight loss, Fatigue",
                      typical_medications="Insulin (rapid/long-acting), Pramlintide",
                      prevalence="~0.5% of population", is_chronic=True),
            Condition(name="Hypothyroidism", icd10_code="E03.9", category="Endocrine",
                      description="Underactive thyroid gland producing insufficient hormones",
                      common_symptoms="Fatigue, Weight gain, Cold intolerance, Constipation, Dry skin",
                      typical_medications="Levothyroxine (Synthroid)",
                      prevalence="~5% of US adults", is_chronic=True),
            Condition(name="Hyperthyroidism", icd10_code="E05.90", category="Endocrine",
                      description="Overactive thyroid gland producing excess hormones",
                      common_symptoms="Weight loss, Rapid heartbeat, Heat intolerance, Tremor, Anxiety",
                      typical_medications="Methimazole, Propranolol, Propylthiouracil",
                      prevalence="~1% of US adults", is_chronic=True),
            Condition(name="Hyperlipidemia", icd10_code="E78.5", category="Endocrine",
                      description="Elevated levels of lipids (cholesterol, triglycerides) in blood",
                      common_symptoms="Usually asymptomatic; detected via blood tests",
                      typical_medications="Atorvastatin, Rosuvastatin, Ezetimibe, Fenofibrate",
                      prevalence="~38% of US adults", is_chronic=True),
            Condition(name="Obesity", icd10_code="E66.01", category="Endocrine",
                      description="Excessive body fat accumulation (BMI >= 30)",
                      common_symptoms="Excess weight, Fatigue, Joint pain, Sleep apnea",
                      typical_medications="Semaglutide, Tirzepatide, Phentermine, Orlistat",
                      prevalence="~42% of US adults", is_chronic=True),

            # Psychiatric
            Condition(name="Major Depressive Disorder", icd10_code="F33.0", category="Psychiatric",
                      description="Persistent depressed mood and loss of interest in activities",
                      common_symptoms="Depressed mood, Loss of interest, Fatigue, Sleep changes, Appetite changes",
                      typical_medications="Sertraline, Fluoxetine, Escitalopram, Venlafaxine, Bupropion",
                      prevalence="~8% of US adults", is_chronic=True),
            Condition(name="Generalized Anxiety Disorder", icd10_code="F41.1", category="Psychiatric",
                      description="Excessive persistent worry about various matters",
                      common_symptoms="Anxiety, Restlessness, Fatigue, Difficulty concentrating, Insomnia",
                      typical_medications="Escitalopram, Sertraline, Buspirone, Venlafaxine, Duloxetine",
                      prevalence="~3% of US adults", is_chronic=True),
            Condition(name="Bipolar Disorder", icd10_code="F31.9", category="Psychiatric",
                      description="Mood disorder with episodes of mania and depression",
                      common_symptoms="Mood swings, Mania, Depression, Insomnia, Impulsivity",
                      typical_medications="Lamotrigine, Lithium, Valproate, Quetiapine, Olanzapine",
                      prevalence="~2.8% of US adults", is_chronic=True),
            Condition(name="ADHD", icd10_code="F90.9", category="Psychiatric",
                      description="Neurodevelopmental disorder with inattention and/or hyperactivity",
                      common_symptoms="Difficulty concentrating, Hyperactivity, Impulsivity, Disorganization",
                      typical_medications="Adderall, Methylphenidate, Atomoxetine, Lisdexamfetamine",
                      prevalence="~4.4% of US adults", is_chronic=True),
            Condition(name="PTSD", icd10_code="F43.10", category="Psychiatric",
                      description="Disorder following traumatic event with re-experiencing and avoidance",
                      common_symptoms="Flashbacks, Nightmares, Anxiety, Hypervigilance, Avoidance",
                      typical_medications="Sertraline, Paroxetine, Venlafaxine, Prazosin",
                      prevalence="~3.6% of US adults", is_chronic=True),
            Condition(name="Schizophrenia", icd10_code="F20.9", category="Psychiatric",
                      description="Chronic disorder affecting thought processes, perceptions, and behavior",
                      common_symptoms="Hallucinations, Delusions, Disorganized speech, Social withdrawal",
                      typical_medications="Risperidone, Olanzapine, Aripiprazole, Clozapine",
                      prevalence="~1% of population", is_chronic=True),
            Condition(name="Insomnia Disorder", icd10_code="G47.00", category="Psychiatric",
                      description="Chronic difficulty falling or staying asleep",
                      common_symptoms="Insomnia, Fatigue, Difficulty concentrating, Mood disturbance",
                      typical_medications="Zolpidem, Trazodone, Melatonin, Suvorexant",
                      prevalence="~10% of US adults", is_chronic=True),

            # Gastrointestinal
            Condition(name="GERD", icd10_code="K21.0", category="Gastrointestinal",
                      description="Chronic acid reflux causing heartburn and esophageal irritation",
                      common_symptoms="Heartburn, Regurgitation, Chest pain, Chronic cough",
                      typical_medications="Omeprazole, Esomeprazole, Pantoprazole, Famotidine",
                      prevalence="~20% of US adults", is_chronic=True),
            Condition(name="Irritable Bowel Syndrome", icd10_code="K58.9", category="Gastrointestinal",
                      description="Functional bowel disorder with abdominal pain and altered bowel habits",
                      common_symptoms="Abdominal pain, Bloating, Diarrhea, Constipation",
                      typical_medications="Dicyclomine, Linaclotide, Rifaximin, Loperamide",
                      prevalence="~12% of US adults", is_chronic=True),
            Condition(name="Peptic Ulcer Disease", icd10_code="K27.9", category="Gastrointestinal",
                      description="Open sores on the inner lining of stomach or upper small intestine",
                      common_symptoms="Abdominal pain, Bloating, Nausea, Heartburn",
                      typical_medications="Omeprazole, Clarithromycin, Amoxicillin, Bismuth"),
            Condition(name="Celiac Disease", icd10_code="K90.0", category="Gastrointestinal",
                      description="Autoimmune disorder triggered by gluten causing intestinal damage",
                      common_symptoms="Diarrhea, Bloating, Weight loss, Fatigue, Anemia",
                      typical_medications="Gluten-free diet (primary treatment), Iron, Calcium, Vitamin D",
                      prevalence="~1% of population", is_chronic=True),

            # Musculoskeletal
            Condition(name="Osteoarthritis", icd10_code="M19.90", category="Musculoskeletal",
                      description="Degenerative joint disease with cartilage breakdown",
                      common_symptoms="Joint pain, Stiffness, Swelling, Reduced range of motion",
                      typical_medications="Acetaminophen, Ibuprofen, Naproxen, Diclofenac, Celecoxib",
                      prevalence="~33 million US adults", is_chronic=True),
            Condition(name="Rheumatoid Arthritis", icd10_code="M06.9", category="Musculoskeletal",
                      description="Autoimmune disorder causing chronic joint inflammation",
                      common_symptoms="Joint pain, Swelling, Stiffness, Fatigue, Fever",
                      typical_medications="Methotrexate, Hydroxychloroquine, Adalimumab, Prednisone",
                      prevalence="~1.3 million US adults", is_chronic=True),
            Condition(name="Fibromyalgia", icd10_code="M79.7", category="Musculoskeletal",
                      description="Widespread musculoskeletal pain with fatigue and cognitive issues",
                      common_symptoms="Widespread pain, Fatigue, Sleep disturbance, Cognitive fog",
                      typical_medications="Pregabalin, Duloxetine, Milnacipran, Gabapentin, Amitriptyline",
                      prevalence="~2% of US adults", is_chronic=True),
            Condition(name="Osteoporosis", icd10_code="M81.0", category="Musculoskeletal",
                      description="Low bone density increasing fracture risk",
                      common_symptoms="Usually asymptomatic until fracture; Back pain, Height loss",
                      typical_medications="Alendronate, Risedronate, Denosumab, Calcium, Vitamin D",
                      prevalence="~10 million US adults", is_chronic=True),
            Condition(name="Gout", icd10_code="M10.9", category="Musculoskeletal",
                      description="Inflammatory arthritis caused by uric acid crystal deposits",
                      common_symptoms="Sudden severe joint pain, Swelling, Redness, Warmth",
                      typical_medications="Colchicine, Indomethacin, Allopurinol, Febuxostat",
                      prevalence="~4% of US adults", is_chronic=True),

            # Infectious
            Condition(name="Urinary Tract Infection", icd10_code="N39.0", category="Infectious",
                      description="Bacterial infection in any part of the urinary system",
                      common_symptoms="Painful urination, Frequent urination, Urgency, Cloudy urine",
                      typical_medications="Nitrofurantoin, TMP-SMX, Ciprofloxacin, Cephalexin",
                      prevalence="~8 million visits/year"),
            Condition(name="Community-Acquired Pneumonia", icd10_code="J18.9", category="Infectious",
                      description="Lung infection acquired outside of hospital setting",
                      common_symptoms="Cough, Fever, Chills, Shortness of breath, Pleuritic pain",
                      typical_medications="Amoxicillin, Azithromycin, Doxycycline, Levofloxacin"),
            Condition(name="Influenza", icd10_code="J11.1", category="Infectious",
                      description="Viral respiratory infection caused by influenza viruses",
                      common_symptoms="Fever, Cough, Body aches, Fatigue, Headache",
                      typical_medications="Oseltamivir (Tamiflu), Baloxavir, Supportive care"),
            Condition(name="COVID-19", icd10_code="U07.1", category="Infectious",
                      description="Respiratory illness caused by SARS-CoV-2 coronavirus",
                      common_symptoms="Fever, Cough, Fatigue, Loss of taste/smell, Shortness of breath",
                      typical_medications="Paxlovid, Remdesivir, Dexamethasone, Supportive care"),

            # Dermatological
            Condition(name="Eczema (Atopic Dermatitis)", icd10_code="L30.9", category="Dermatological",
                      description="Chronic skin inflammation causing itchy, red, dry patches",
                      common_symptoms="Itching, Rash, Dry skin, Redness, Skin cracking",
                      typical_medications="Hydrocortisone, Triamcinolone, Tacrolimus, Dupilumab",
                      prevalence="~10% of US adults", is_chronic=True),
            Condition(name="Psoriasis", icd10_code="L40.9", category="Dermatological",
                      description="Autoimmune condition causing rapid skin cell buildup forming scales",
                      common_symptoms="Red patches, Silvery scales, Itching, Dry cracked skin",
                      typical_medications="Methotrexate, Adalimumab, Apremilast, Topical steroids",
                      prevalence="~3% of US adults", is_chronic=True),
            Condition(name="Acne Vulgaris", icd10_code="L70.0", category="Dermatological",
                      description="Skin condition causing pimples, blackheads, and cysts",
                      common_symptoms="Pimples, Blackheads, Whiteheads, Oily skin",
                      typical_medications="Tretinoin, Benzoyl peroxide, Doxycycline, Isotretinoin",
                      prevalence="~50 million US annually", is_chronic=True),

            # Neurological
            Condition(name="Migraine", icd10_code="G43.909", category="Neurological",
                      description="Recurrent headaches with throbbing pain, often with aura",
                      common_symptoms="Severe headache, Nausea, Light sensitivity, Visual aura",
                      typical_medications="Sumatriptan, Topiramate, Propranolol, Amitriptyline, CGRP inhibitors",
                      prevalence="~12% of US population", is_chronic=True),
            Condition(name="Epilepsy", icd10_code="G40.909", category="Neurological",
                      description="Chronic disorder with recurrent unprovoked seizures",
                      common_symptoms="Seizures, Confusion, Staring, Loss of awareness",
                      typical_medications="Levetiracetam, Lamotrigine, Valproate, Carbamazepine",
                      prevalence="~1.2% of US population", is_chronic=True),
            Condition(name="Parkinson's Disease", icd10_code="G20", category="Neurological",
                      description="Progressive nervous system disorder affecting movement",
                      common_symptoms="Tremor, Bradykinesia, Rigidity, Balance problems",
                      typical_medications="Levodopa/Carbidopa, Pramipexole, Rasagiline, Amantadine",
                      prevalence="~1 million US adults", is_chronic=True),
            Condition(name="Multiple Sclerosis", icd10_code="G35", category="Neurological",
                      description="Autoimmune disease affecting brain and spinal cord nerve coverings",
                      common_symptoms="Numbness, Vision problems, Fatigue, Balance issues, Weakness",
                      typical_medications="Interferon beta, Glatiramer, Dimethyl fumarate, Ocrelizumab",
                      prevalence="~1 million US adults", is_chronic=True),
            Condition(name="Alzheimer's Disease", icd10_code="G30.9", category="Neurological",
                      description="Progressive brain disorder causing memory loss and cognitive decline",
                      common_symptoms="Memory loss, Confusion, Language problems, Personality changes",
                      typical_medications="Donepezil, Memantine, Rivastigmine, Lecanemab",
                      prevalence="~6.7 million US adults 65+", is_chronic=True),

            # Renal
            Condition(name="Chronic Kidney Disease", icd10_code="N18.9", category="Renal",
                      description="Gradual loss of kidney function over time",
                      common_symptoms="Fatigue, Edema, Nausea, Decreased urine output",
                      typical_medications="Lisinopril, Losartan, Empagliflozin, Sodium bicarbonate",
                      prevalence="~15% of US adults", is_chronic=True),
            Condition(name="Kidney Stones", icd10_code="N20.0", category="Renal",
                      description="Hard mineral deposits forming in the kidneys",
                      common_symptoms="Severe flank pain, Hematuria, Nausea, Painful urination",
                      typical_medications="Tamsulosin, Ketorolac, Potassium citrate, Hydrochlorothiazide"),

            # Hematological
            Condition(name="Iron Deficiency Anemia", icd10_code="D50.9", category="Hematological",
                      description="Insufficient healthy red blood cells due to low iron",
                      common_symptoms="Fatigue, Weakness, Pale skin, Shortness of breath, Dizziness",
                      typical_medications="Ferrous sulfate, Iron infusion, Vitamin C (absorption aid)",
                      prevalence="~5% of US population"),
        ]
        session.add_all(conditions)
        session.flush()

        # ── Additional Medications (30+ more) ─────────────────────────
        extra_meds = [
            Medication(ndc_code="0093-7180-01", brand_name="Amlodipine", generic_name="Amlodipine Besylate",
                       manufacturer="Pfizer", drug_class="Antihypertensive - CCB", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="5mg", unit="mg",
                       description="Calcium channel blocker for hypertension and angina",
                       indications="Hypertension, Coronary artery disease, Angina",
                       contraindications="Severe aortic stenosis, Cardiogenic shock",
                       side_effects="Edema, Dizziness, Flushing, Headache",
                       avg_wholesale_price=2.50, retail_price=8.99),
            Medication(ndc_code="0781-5180-01", brand_name="Losartan", generic_name="Losartan Potassium",
                       manufacturer="Merck", drug_class="Antihypertensive - ARB", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="50mg", unit="mg",
                       description="Angiotensin II receptor blocker for hypertension",
                       indications="Hypertension, Diabetic nephropathy, Stroke prevention",
                       contraindications="Pregnancy, Bilateral renal artery stenosis",
                       side_effects="Dizziness, Hyperkalemia, Fatigue, Cough (rare)",
                       avg_wholesale_price=3.00, retail_price=11.99),
            Medication(ndc_code="0378-1800-01", brand_name="Omeprazole", generic_name="Omeprazole",
                       manufacturer="AstraZeneca", drug_class="PPI - Proton Pump Inhibitor", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.CAPSULE, strength="20mg", unit="mg",
                       description="Proton pump inhibitor reducing stomach acid production",
                       indications="GERD, Peptic ulcer, H. pylori (with antibiotics), Zollinger-Ellison",
                       contraindications="Rilpivirine coadministration",
                       side_effects="Headache, Nausea, Diarrhea, B12 deficiency (long-term)",
                       avg_wholesale_price=2.00, retail_price=9.99),
            Medication(ndc_code="0069-2650-30", brand_name="Celebrex", generic_name="Celecoxib",
                       manufacturer="Pfizer", drug_class="NSAID - COX-2 Inhibitor", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.CAPSULE, strength="200mg", unit="mg",
                       description="Selective COX-2 inhibitor anti-inflammatory",
                       indications="Osteoarthritis, Rheumatoid arthritis, Acute pain, Ankylosing spondylitis",
                       contraindications="Sulfonamide allergy, Post-CABG surgery, Active GI bleeding",
                       side_effects="Abdominal pain, Diarrhea, CV risk, Renal effects",
                       avg_wholesale_price=8.00, retail_price=32.99),
            Medication(ndc_code="0049-3900-73", brand_name="Lyrica", generic_name="Pregabalin",
                       manufacturer="Pfizer", drug_class="Anticonvulsant - Gabapentinoid", schedule=DrugSchedule.V,
                       route=DrugRoute.ORAL, form=DrugForm.CAPSULE, strength="75mg", unit="mg",
                       description="Gabapentinoid for neuropathic pain and seizures",
                       indications="Fibromyalgia, Diabetic neuropathy, Postherpetic neuralgia, Seizures",
                       contraindications="Known hypersensitivity",
                       side_effects="Dizziness, Somnolence, Weight gain, Peripheral edema",
                       avg_wholesale_price=6.00, retail_price=24.99, is_controlled=True),
            Medication(ndc_code="0006-0749-31", brand_name="Januvia", generic_name="Sitagliptin",
                       manufacturer="Merck", drug_class="Antidiabetic - DPP-4 Inhibitor", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="100mg", unit="mg",
                       description="DPP-4 inhibitor for type 2 diabetes blood sugar control",
                       indications="Type 2 diabetes mellitus (adjunct to diet and exercise)",
                       contraindications="Type 1 diabetes, Diabetic ketoacidosis",
                       side_effects="Upper respiratory infection, Headache, Nasopharyngitis",
                       avg_wholesale_price=15.00, retail_price=45.99),
            Medication(ndc_code="0597-0135-37", brand_name="Coreg", generic_name="Carvedilol",
                       manufacturer="GlaxoSmithKline", drug_class="Antihypertensive - Beta Blocker", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="25mg", unit="mg",
                       description="Non-selective beta blocker with alpha-blocking activity",
                       indications="Heart failure, Hypertension, Post-MI left ventricular dysfunction",
                       contraindications="Bronchial asthma, Severe bradycardia, Heart block",
                       side_effects="Dizziness, Fatigue, Hypotension, Bradycardia, Weight gain",
                       avg_wholesale_price=3.00, retail_price=12.99),
            Medication(ndc_code="0378-6150-01", brand_name="Furosemide", generic_name="Furosemide",
                       manufacturer="Sanofi", drug_class="Diuretic - Loop", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="40mg", unit="mg",
                       description="Loop diuretic for fluid retention and edema",
                       indications="Heart failure edema, Renal disease edema, Hepatic cirrhosis, Hypertension",
                       contraindications="Anuria, Hepatic coma, Severe electrolyte depletion",
                       side_effects="Dehydration, Electrolyte imbalance, Hypotension, Ototoxicity",
                       avg_wholesale_price=2.00, retail_price=7.99),
            Medication(ndc_code="0173-0519-00", brand_name="Advair Diskus", generic_name="Fluticasone/Salmeterol",
                       manufacturer="GlaxoSmithKline", drug_class="Respiratory - ICS/LABA Combination", schedule=DrugSchedule.NONE,
                       route=DrugRoute.INHALATION, form=DrugForm.INHALER, strength="250/50mcg", unit="mcg",
                       description="Combination inhaler for asthma and COPD maintenance",
                       indications="Asthma maintenance, COPD maintenance",
                       contraindications="Status asthmaticus, Acute bronchospasm",
                       side_effects="Oral candidiasis, Hoarseness, Headache, Upper respiratory infection",
                       avg_wholesale_price=20.00, retail_price=65.99),
            Medication(ndc_code="0069-4220-30", brand_name="Norvasc", generic_name="Amlodipine",
                       manufacturer="Pfizer", drug_class="Antihypertensive - CCB", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="10mg", unit="mg",
                       description="Calcium channel blocker for hypertension (higher dose)",
                       indications="Hypertension, Chronic stable angina, Vasospastic angina",
                       contraindications="Severe aortic stenosis",
                       side_effects="Peripheral edema, Dizziness, Flushing, Palpitations",
                       avg_wholesale_price=3.00, retail_price=10.99),
            Medication(ndc_code="0078-0401-05", brand_name="Diovan", generic_name="Valsartan",
                       manufacturer="Novartis", drug_class="Antihypertensive - ARB", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="160mg", unit="mg",
                       description="Angiotensin II receptor blocker",
                       indications="Hypertension, Heart failure, Post-MI",
                       contraindications="Pregnancy, Bilateral renal artery stenosis",
                       side_effects="Dizziness, Headache, Hyperkalemia, Fatigue",
                       avg_wholesale_price=5.00, retail_price=18.99),
            Medication(ndc_code="0074-3289-13", brand_name="Humira", generic_name="Adalimumab",
                       manufacturer="AbbVie", drug_class="Biologic - TNF Inhibitor", schedule=DrugSchedule.NONE,
                       route=DrugRoute.SUBCUTANEOUS, form=DrugForm.INJECTION, strength="40mg/0.4mL", unit="mg",
                       description="TNF-alpha inhibitor for autoimmune conditions",
                       indications="Rheumatoid arthritis, Psoriasis, Crohn's disease, Ulcerative colitis",
                       contraindications="Active infections, Active TB",
                       side_effects="Injection site reactions, Infections, Headache",
                       avg_wholesale_price=2800.00, retail_price=5500.00),
            Medication(ndc_code="59148-0040-00", brand_name="Ozempic", generic_name="Semaglutide",
                       manufacturer="Novo Nordisk", drug_class="Antidiabetic - GLP-1 Agonist", schedule=DrugSchedule.NONE,
                       route=DrugRoute.SUBCUTANEOUS, form=DrugForm.INJECTION, strength="1mg/dose", unit="mg",
                       description="GLP-1 receptor agonist for type 2 diabetes and weight management",
                       indications="Type 2 diabetes mellitus, Cardiovascular risk reduction",
                       contraindications="Medullary thyroid carcinoma, MEN 2 syndrome",
                       side_effects="Nausea, Vomiting, Diarrhea, Abdominal pain, Pancreatitis risk",
                       avg_wholesale_price=850.00, retail_price=1200.00),
            Medication(ndc_code="0002-1433-80", brand_name="Trulicity", generic_name="Dulaglutide",
                       manufacturer="Eli Lilly", drug_class="Antidiabetic - GLP-1 Agonist", schedule=DrugSchedule.NONE,
                       route=DrugRoute.SUBCUTANEOUS, form=DrugForm.INJECTION, strength="1.5mg/0.5mL", unit="mg",
                       description="Once-weekly GLP-1 receptor agonist for type 2 diabetes",
                       indications="Type 2 diabetes mellitus, Cardiovascular risk reduction",
                       contraindications="Medullary thyroid carcinoma history, MEN 2 syndrome",
                       side_effects="Nausea, Diarrhea, Vomiting, Abdominal pain, Decreased appetite",
                       avg_wholesale_price=780.00, retail_price=1100.00),
            Medication(ndc_code="0078-0620-61", brand_name="Entresto", generic_name="Sacubitril/Valsartan",
                       manufacturer="Novartis", drug_class="Heart Failure - ARNI", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="49/51mg", unit="mg",
                       description="Angiotensin receptor-neprilysin inhibitor for heart failure",
                       indications="Heart failure with reduced ejection fraction (HFrEF)",
                       contraindications="ACE inhibitor use within 36 hours, Angioedema history",
                       side_effects="Hypotension, Hyperkalemia, Renal impairment, Cough",
                       avg_wholesale_price=16.00, retail_price=55.99),
            Medication(ndc_code="50580-0449-70", brand_name="Tylenol", generic_name="Acetaminophen",
                       manufacturer="Johnson & Johnson", drug_class="Analgesic - Non-opioid", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="500mg", unit="mg",
                       description="Non-opioid analgesic and antipyretic",
                       indications="Mild-moderate pain, Fever reduction",
                       contraindications="Severe hepatic impairment, Active liver disease",
                       side_effects="Hepatotoxicity (overdose), Rare allergic reactions",
                       avg_wholesale_price=1.50, retail_price=6.99),
            Medication(ndc_code="0573-0150-20", brand_name="Ibuprofen", generic_name="Ibuprofen",
                       manufacturer="Advil/Pfizer", drug_class="NSAID", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="200mg", unit="mg",
                       description="Non-steroidal anti-inflammatory drug",
                       indications="Pain, Inflammation, Fever, Arthritis, Dysmenorrhea",
                       contraindications="Active GI bleeding, Post-CABG, Severe renal impairment",
                       side_effects="GI upset, GI bleeding risk, Renal effects, CV risk",
                       avg_wholesale_price=1.50, retail_price=5.99),
            Medication(ndc_code="0603-5168-21", brand_name="Prednisone", generic_name="Prednisone",
                       manufacturer="Various", drug_class="Corticosteroid", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="10mg", unit="mg",
                       description="Synthetic corticosteroid for inflammation and immune suppression",
                       indications="Inflammatory conditions, Autoimmune disorders, Allergic reactions, Asthma exacerbation",
                       contraindications="Systemic fungal infections, Live vaccines",
                       side_effects="Weight gain, Hyperglycemia, Osteoporosis, Mood changes, Insomnia",
                       avg_wholesale_price=2.00, retail_price=8.99),
            Medication(ndc_code="0093-0058-01", brand_name="Buspirone", generic_name="Buspirone HCl",
                       manufacturer="Bristol-Myers Squibb", drug_class="Anxiolytic - Azapirone", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="10mg", unit="mg",
                       description="Non-benzodiazepine anxiolytic for generalized anxiety",
                       indications="Generalized anxiety disorder",
                       contraindications="MAOIs within 14 days, Severe hepatic/renal impairment",
                       side_effects="Dizziness, Nausea, Headache, Nervousness, Lightheadedness",
                       avg_wholesale_price=3.00, retail_price=12.99),
            Medication(ndc_code="0074-6415-13", brand_name="Depakote", generic_name="Divalproex Sodium",
                       manufacturer="AbbVie", drug_class="Anticonvulsant - Mood Stabilizer", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="500mg", unit="mg",
                       description="Anticonvulsant and mood stabilizer",
                       indications="Epilepsy, Bipolar mania, Migraine prevention",
                       contraindications="Hepatic disease, Urea cycle disorders, Pregnancy",
                       side_effects="Nausea, Tremor, Weight gain, Hair loss, Hepatotoxicity",
                       avg_wholesale_price=5.00, retail_price=18.99),
            Medication(ndc_code="0002-4462-60", brand_name="Cymbalta", generic_name="Duloxetine",
                       manufacturer="Eli Lilly", drug_class="Antidepressant - SNRI", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.CAPSULE, strength="60mg", unit="mg",
                       description="Serotonin-norepinephrine reuptake inhibitor",
                       indications="Major depression, GAD, Diabetic neuropathy, Fibromyalgia, Chronic pain",
                       contraindications="MAOIs within 14 days, Uncontrolled glaucoma",
                       side_effects="Nausea, Dry mouth, Constipation, Fatigue, Dizziness",
                       avg_wholesale_price=6.00, retail_price=22.99),
            Medication(ndc_code="0093-5260-01", brand_name="Metformin ER", generic_name="Metformin Extended-Release",
                       manufacturer="Various", drug_class="Antidiabetic - Biguanide", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="750mg", unit="mg",
                       description="Extended-release biguanide for type 2 diabetes",
                       indications="Type 2 diabetes mellitus, Insulin resistance, PCOS (off-label)",
                       contraindications="eGFR <30, Metabolic acidosis, Acute/chronic metabolic acidosis",
                       side_effects="GI upset (less than IR), Diarrhea, B12 deficiency (long-term)",
                       avg_wholesale_price=3.00, retail_price=10.99),
            Medication(ndc_code="0310-0280-30", brand_name="Jardiance", generic_name="Empagliflozin",
                       manufacturer="Boehringer Ingelheim", drug_class="Antidiabetic - SGLT2 Inhibitor", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="10mg", unit="mg",
                       description="SGLT2 inhibitor for type 2 diabetes with cardiovascular benefits",
                       indications="Type 2 diabetes, Heart failure, Chronic kidney disease",
                       contraindications="Dialysis, Severe renal impairment, Type 1 diabetes",
                       side_effects="UTI, Genital mycotic infections, Hypotension, Ketoacidosis risk",
                       avg_wholesale_price=18.00, retail_price=55.99),
            Medication(ndc_code="0069-1085-30", brand_name="Chantix", generic_name="Varenicline",
                       manufacturer="Pfizer", drug_class="Smoking Cessation Aid", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="1mg", unit="mg",
                       description="Nicotinic receptor partial agonist for smoking cessation",
                       indications="Smoking cessation aid (adult tobacco dependence)",
                       contraindications="Known hypersensitivity",
                       side_effects="Nausea, Insomnia, Abnormal dreams, Headache",
                       avg_wholesale_price=8.00, retail_price=28.99),
            Medication(ndc_code="0006-0277-31", brand_name="Cozaar", generic_name="Losartan",
                       manufacturer="Merck", drug_class="Antihypertensive - ARB", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="100mg", unit="mg",
                       description="Angiotensin II receptor blocker (higher dose)",
                       indications="Hypertension, Stroke prevention, Diabetic nephropathy",
                       contraindications="Pregnancy, Aliskiren in diabetic patients",
                       side_effects="Dizziness, Upper respiratory infection, Hyperkalemia",
                       avg_wholesale_price=4.00, retail_price=14.99),
            Medication(ndc_code="0078-0357-15", brand_name="Ritalin", generic_name="Methylphenidate",
                       manufacturer="Novartis", drug_class="CNS Stimulant", schedule=DrugSchedule.II,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="10mg", unit="mg",
                       description="CNS stimulant for ADHD and narcolepsy",
                       indications="ADHD, Narcolepsy",
                       contraindications="MAOIs within 14 days, Glaucoma, Severe anxiety/agitation",
                       side_effects="Insomnia, Decreased appetite, Headache, Tachycardia, Nervousness",
                       avg_wholesale_price=12.00, retail_price=38.99, is_controlled=True),
            Medication(ndc_code="0074-2214-13", brand_name="Synthroid", generic_name="Levothyroxine (100mcg)",
                       manufacturer="AbbVie", drug_class="Thyroid Hormone", schedule=DrugSchedule.NONE,
                       route=DrugRoute.ORAL, form=DrugForm.TABLET, strength="100mcg", unit="mcg",
                       description="Synthetic thyroid hormone replacement (higher dose)",
                       indications="Hypothyroidism, Thyroid cancer (TSH suppression), Myxedema coma",
                       contraindications="Untreated adrenal insufficiency, Acute MI",
                       side_effects="Palpitations, Weight loss, Tremor, Insomnia (if overdosed)",
                       avg_wholesale_price=4.00, retail_price=14.99),
        ]
        session.add_all(extra_meds)
        session.flush()
        print(f"  Seeded {len(symptoms)} symptoms, {len(conditions)} conditions, {len(extra_meds)} additional medications")
