/*
 * MedPharm ERP - iOS Application
 * Copyright (C) 2026 Enlightec Ltd. (www.enlightec.com)
 * Author: Robert Andrew Stillwell
 * Email: Andrew.Stillwell@enlightec.com
 * License: GNU General Public License v3.0
 *
 * QRScannerView — A SwiftUI sheet that wraps an AVCaptureSession and looks
 * for QR codes encoding a MedPharm API base URL (typically generated by the
 * server-side `start_ngrok.sh` script and shipped as data/ngrok_qr.png). The
 * caller receives the decoded string via the `onResult` closure and may
 * dismiss the sheet itself; the scanner stops the capture session as soon
 * as a code is recognised so the camera is not held longer than necessary.
 *
 * Usage:
 *   .sheet(isPresented: $showScanner) {
 *       QRScannerView { code in
 *           serverURL = code
 *           showScanner = false
 *       }
 *   }
 *
 * Required Info.plist key (add in the Xcode project, not this file):
 *   NSCameraUsageDescription = "MedPharm ERP scans the QR code generated by
 *                               your server administrator to configure the
 *                               API endpoint without typing."
 */

import SwiftUI
import AVFoundation
import UIKit

struct QRScannerView: View {
    var onResult: (String) -> Void
    @Environment(\.dismiss) private var dismiss
    @State private var errorMessage: String?

    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()

            QRScannerRepresentable(onResult: { code in
                onResult(code)
            }, onError: { msg in
                errorMessage = msg
            })
            .ignoresSafeArea()

            VStack {
                HStack {
                    Spacer()
                    Button(action: { dismiss() }) {
                        Image(systemName: "xmark.circle.fill")
                            .font(.system(size: 32))
                            .foregroundStyle(.white, .black.opacity(0.45))
                            .padding(12)
                    }
                    .accessibilityLabel("Close")
                }
                Spacer()
                VStack(spacing: 8) {
                    RoundedRectangle(cornerRadius: 14)
                        .strokeBorder(Color.white.opacity(0.85), lineWidth: 3)
                        .frame(width: 250, height: 250)
                    Text("Align the MedPharm server QR code\ninside the frame")
                        .font(.footnote)
                        .multilineTextAlignment(.center)
                        .foregroundColor(.white.opacity(0.85))
                        .padding(.top, 6)
                }
                Spacer()
                if let msg = errorMessage {
                    Text(msg)
                        .font(.caption)
                        .foregroundColor(.white)
                        .padding(.horizontal, 14)
                        .padding(.vertical, 10)
                        .background(RoundedRectangle(cornerRadius: 10).fill(Color.red.opacity(0.85)))
                        .padding(.bottom, 28)
                }
            }
        }
    }
}

// MARK: - UIKit bridge

struct QRScannerRepresentable: UIViewControllerRepresentable {
    var onResult: (String) -> Void
    var onError: (String) -> Void

    func makeUIViewController(context: Context) -> QRScannerViewController {
        let vc = QRScannerViewController()
        vc.onResult = onResult
        vc.onError = onError
        return vc
    }

    func updateUIViewController(_ uiViewController: QRScannerViewController, context: Context) {}
}

final class QRScannerViewController: UIViewController, AVCaptureMetadataOutputObjectsDelegate {
    var onResult: ((String) -> Void)?
    var onError: ((String) -> Void)?

    private let session = AVCaptureSession()
    private var previewLayer: AVCaptureVideoPreviewLayer?
    private var hasReported = false

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .black

        AVCaptureDevice.requestAccess(for: .video) { [weak self] granted in
            DispatchQueue.main.async {
                guard let self = self else { return }
                if granted {
                    self.configureSession()
                } else {
                    self.onError?("Camera permission denied. Enable it in Settings to scan a QR code.")
                }
            }
        }
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        if session.inputs.count > 0 && !session.isRunning {
            DispatchQueue.global(qos: .userInitiated).async { [weak self] in
                self?.session.startRunning()
            }
        }
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        if session.isRunning {
            session.stopRunning()
        }
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        previewLayer?.frame = view.bounds
    }

    private func configureSession() {
        guard let device = AVCaptureDevice.default(for: .video) else {
            onError?("No camera available on this device.")
            return
        }

        do {
            let input = try AVCaptureDeviceInput(device: device)
            if session.canAddInput(input) {
                session.addInput(input)
            } else {
                onError?("Could not attach the camera to the scanner.")
                return
            }
        } catch {
            onError?("Camera initialisation failed: \(error.localizedDescription)")
            return
        }

        let output = AVCaptureMetadataOutput()
        if session.canAddOutput(output) {
            session.addOutput(output)
            output.setMetadataObjectsDelegate(self, queue: .main)
            output.metadataObjectTypes = [.qr]
        } else {
            onError?("Could not enable QR detection.")
            return
        }

        let layer = AVCaptureVideoPreviewLayer(session: session)
        layer.frame = view.bounds
        layer.videoGravity = .resizeAspectFill
        view.layer.addSublayer(layer)
        self.previewLayer = layer

        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            self?.session.startRunning()
        }
    }

    func metadataOutput(_ output: AVCaptureMetadataOutput,
                        didOutput metadataObjects: [AVMetadataObject],
                        from connection: AVCaptureConnection) {
        guard !hasReported,
              let metadata = metadataObjects.first as? AVMetadataMachineReadableCodeObject,
              metadata.type == .qr,
              let value = metadata.stringValue, !value.isEmpty
        else { return }
        hasReported = true
        let generator = UINotificationFeedbackGenerator()
        generator.notificationOccurred(.success)
        session.stopRunning()
        onResult?(value)
    }
}
