/*
 * MedPharm ERP - Windows Desktop Application
 * Copyright (C) 2026 Enlightec Ltd. (www.enlightec.com)
 * Author: Robert Andrew Stillwell
 * Email: Andrew.Stillwell@enlightec.com
 * License: GNU General Public License v3.0
 *
 * QRConfigParser — Normalises a pasted/scanned string to an API base URL.
 * Mirrors the iOS / Android / macOS implementations so a QR or JSON snippet
 * generated by the server-side `start_ngrok.sh` helper feeds any client
 * identically.
 */

using Newtonsoft.Json.Linq;

namespace MedPharm.Services;

public static class QRConfigParser
{
    public static string Normalize(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return string.Empty;
        var trimmed = raw.Trim();

        if (trimmed.StartsWith("{"))
        {
            try
            {
                var obj = JObject.Parse(trimmed);
                var apiBase = (string?)obj["api_base_url"];
                if (!string.IsNullOrEmpty(apiBase)) return apiBase!;

                var publicUrl = (string?)obj["public_url"];
                if (!string.IsNullOrEmpty(publicUrl))
                    return AppendApiSuffixIfMissing(publicUrl!);
            }
            catch
            {
                // Fall through to URL handling.
            }
        }

        var lower = trimmed.ToLowerInvariant();
        if (lower.StartsWith("http://") || lower.StartsWith("https://"))
        {
            return AppendApiSuffixIfMissing(trimmed);
        }

        return trimmed;
    }

    private static string AppendApiSuffixIfMissing(string url)
    {
        var stripped = url.EndsWith("/") ? url.Substring(0, url.Length - 1) : url;
        return stripped.Contains("/api/") ? stripped : stripped + "/api/v1";
    }
}
