apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medpharm

labels:
  - pairs:
      app.kubernetes.io/name: medpharm
      app.kubernetes.io/part-of: medpharm-erp
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: enlightec/medpharm-server
    newTag: "1.6.0"
